### ISSUE TITLE
Clean the spreadsheet

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/plot_the_dots#9] opened 2020-01-27 22:17 UTC
The app should provide some basic tools to deal with ugly spreadsheets- e.g. reading the headers from rows other than row 1, maybe even cleaning up spaces a bit

**Comment by tomjemmett** [comment] 2020-01-28 08:48
duplicate of #6: I think we shouldn't be too ambitious with cleaning the data. I think the app should aim to produce SPC charts and that's it (keeps the project simpler for us!) but we may want to review this overtime.

**Closed by tomjemmett** 2020-01-28 08:48 UTC
